- name: Import Microsoft APT key
  apt_key:
    url: "https://packages.microsoft.com/keys/microsoft.asc"
    state: present
  become: yes
  
- name: Install deb package
  apt:
    deb:  https://packages.microsoft.com/config/ubuntu/{{ ansible_distribution_version }}/packages-microsoft-prod.deb
    state: present
  become: yes

- name: Install .NET 5.0 SDK
  apt:
    update_cache: yes 
    name: dotnet-sdk-5.0
    state: present
  become: yes